### ISSUE TITLE
employer dashboard

### ISSUE THREAD

**Issue by jackson-** [jackson-/hireblack.io#5]
- [x] see listing history w/ links to edit current listings
- [x] edit profile info
- [x] view applicants (by listing)
- [x] candidate search ? (should this this replace job search on home page if isEmployer = true??)

**Comment by chloerice** [comment]
- [ ] see listing history w/ links to edit current listings
- [ ] edit profile info
- [ ] view applicants (by listing)
- [ ] candidate search ? (should this this replace job search on home page if isEmployer = true??)
